apiVersion: v1
kind: ConfigMap
metadata:
  name: ovms-config
  namespace: default
data:
  ovms_config.json: |
    {
    "model_config_list": [
         {
            "config": {
                 "name": "resnet50-int8",
                 "base_path": "gs://ovms-public-eu/resnet50-binary"
            }
         }
     ],
     "monitoring":
         {
             "metrics":
             {
                 "enable": true
             }
         }
    }
