apiVersion: intel.com/v1alpha1
kind: ModelServer
metadata:
  name: ovms-sample
spec:
  annotations: {}
  aws_access_key_id: ""
  aws_region: ""
  aws_secret_access_key: ""
  s3_compat_api_endpoint: ""
  config_configmap_name: ""
  gcp_creds_secret_name: ""
  grpc_port: 8080
  rest_port: 8081
  image_name: openvino/model_server:latest
  log_level: INFO
  model_name: "resnet"
  model_path: "gs://ovms-public-eu/resnet50-binary"
  models_host_path: ""
  models_volume_claim: ""
  nireq: ""
  plugin_config: '{\"CPU_THROUGHPUT_STREAMS\":\"1\"}'
  batch_size: ""
  shape: ""
  model_version_policy: '{\"latest\": { \"num_versions\":1 }}'
  file_system_poll_wait_seconds: 0
  replicas: 1
  resources:
    limits:
      cpu: 4
      memory: 250Mi
  security_context: {}
  service_type: LoadBalancer
  target_device: CPU
  https_proxy: ""


  
