apiVersion: intel.com/v1alpha1
kind: ModelServer
metadata:
  name: ovms-sample
spec:
  image_name: openvino/model_server:latest
  deployment_parameters:
    replicas: 1
    openshift_service_mesh: false
  models_settings:
    single_model_mode: true
    config_configmap_name: ""
    model_config: ""   
    model_name: "resnet"
    model_path: "gs://ovms-public-eu/resnet50-binary"
    nireq: 0
    plugin_config: '{"CPU_THROUGHPUT_STREAMS":"1"}'
    batch_size: ""
    shape: ""
    model_version_policy: '{"latest": {"num_versions":1 }}'
    layout: ""
    target_device: "CPU"
    is_stateful: false
    idle_sequence_cleanup: false
    low_latency_transformation: true
    max_sequence_number: 0
  server_settings:
    file_system_poll_wait_seconds: 0
    sequence_cleaner_poll_wait_minutes: 0
    log_level: "INFO"
    grpc_workers: 1
    rest_workers: 0
  service_parameters:
    port_grpc: 8080
    port_rest: 8081
    service_type: ClusterIP
  models_repository:
    storage_type: google




  
