apiVersion: intel.com/v1alpha1
kind: ModelServer
metadata:
  name: ovms-sample
spec:
  image_name: openvino/model_server:latest
  deployment_parameters:
    node_selector: ""
    annotations: {}
    resources: {}
    replicas: 1 
  config_file:
    config_configmap_name: ""
    model_config_path: ""
  model_settings:
    model_name: "resnet"
    model_path: "gs://ovms-public-eu/resnet50-binary"
    nireq: 0
    plugin_config: '{\"CPU_THROUGHPUT_STREAMS\":\"1\"}'
    batch_size: ""
    shape: ""
    model_version_policy: '{\"latest\": { \"num_versions\":1 }}'
    layout: ""
    target_device: "CPU"
    stateful:
      stateful: false
      idle_sequence_cleanup: false
      low_latency_transformation: true
      max_sequence_number: 0
  server:
    file_system_poll_wait_seconds: 0
    sequence_cleaner_poll_wait_minutes: 0
    log_level: "INFO"
    grpc_workers: 1
    rest_workers: 0
    ports:
      grpc_port: 8080
      rest_port: 8081
  models_repository:
    https_proxy: "http://proxy-mu.intel.com:911"
    http_proxy: ""
    cluster_storage:
      models_host_path: ""
      models_volume_claim: ""
      security_context: {}
    aws:
      aws_secret_access_key: ""
      aws_access_key_id: ""
      aws_region: ""
      s3_compat_api_endpoint: ""
    gcs:
      gcp_creds_secret_name: ""
    azure:
      azure_storage_connection_string: ""




  
