apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: model-server-sample-scaling
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - memory
        maxAllowed:
          memory: 1000Mi
        minAllowed:
          memory: 250Mi
  targetRef:
    apiVersion: intel.com/v1alpha1
    kind: ModelServer
    name: model-server-sample
  updatePolicy:
    updateMode: Auto